### PR TITLE
Fix undefined cli flags override config

### LINKED ISSUE #54: CLI options should override config file
Currently I think CLI options are overridden by the config file:

``` js
var opts = assign({}, {
      minify: program.minify,
      root: program.importRoot,
      lint: program.lint
    }, config);
```

AFAIK it's most common to be the other way round as it's often useful to be able to override a single config option on the CLI.

Should be a simple change and maybe a test to verify.

### PR DESCRIPTION
**Pull request by giuseppeg**
When cli flags are not passed their value is `undefined` and they override the config file options.
This branch fixes this behaviour.

Fixes #54

### CODE REVIEW

**Comment by simonsmith** [comment]
Looks good. Just need a `CHANGELOG` update and for some reason your commit isn't associated with your user:

screen shot 2016-11-13 at 14 46 57

**Comment by giuseppeg** [comment]
@simonsmith can you restart the appveyor build?

**Comment by simonsmith** [comment]
Restarted. I think I can add you to the Appveyor project if you let me know preferred email.

**Comment by giuseppeg** [comment]
thanks @simonsmith ! can I merge this?

**Comment by simonsmith** [comment]
Yup

**Pull request merged**
