### PR TITLE
Allow re-ordering of the plugins array via config

### PR DESCRIPTION
**Pull request by simonsmith**
This allows users to add plugins to the existing array as normal, but also gives them control over re-ordering existing ones. 

Currently `object-assign-deep` just concats arrays, which means there is no order control.

Say for example I need `stylelint` to run before `autoprefixer`:

```js
// defaults
[
    'postcss-import',
    'postcss-custom-properties',
    'postcss-calc',
    'postcss-custom-media',
    'autoprefixer',
    'postcss-reporter'
  ]

// config
{use: ['stylelint', 'autoprefixer', 'postcss-reporter']}

// result
[
    'postcss-import',
    'postcss-custom-properties',
    'postcss-calc',
    'postcss-custom-media',
    'stylelint',
    'autoprefixer',
    'postcss-reporter'
  ]
```

This could also be useful to re-order the existing plugins if needed.

```js
// config
{use: ['autoprefixer', 'postcss-at2x', 'postcss-calc', 'postcss-reporter']}

// result
[
  'postcss-import',
  'postcss-custom-properties',
  'postcss-custom-media',
  'autoprefixer',
  'postcss-at2x',
  'postcss-calc',
  'postcss-reporter'
]
```

This need came out of trying to get `stylelint` to work and having `autoprefixer` get in the way, but I think it's a nice enhancement anyway.

I removed the check for `postcss-reporter` being last, because now the user has control over that easily.

Also made the lodash dependency smaller by using the individual packages, but annoyingly I think `postcss-reporter` uses the full library anyway.

@giuseppeg If this looks good I'll update the README too :)

### CODE REVIEW

**Comment by giuseppeg** [comment]
@simonsmith yeah it looks good! I wonder if `deepmerge` was doing that already.

**Comment by simonsmith** [comment]
Good question! I will investigate first

**Comment by simonsmith** [comment]
It does dedupe arrays, but not in the way that would work for this - http://jsbin.com/genuci/edit?js,console

**Comment by giuseppeg** [comment]
fair enough, I just asked out of curiosity ;)

**Comment by simonsmith** [comment]
Would have been handy!

**Pull request merged**
