### PR TITLE
Add ESLint

### PR DESCRIPTION
**Pull request by simonsmith**
I've used the AirBnB styleguide as the base as most of it seems sensible and then just tweaked a few rules based on patterns already used here, like reassigning parameters. 

It will fail the tests too.

### CODE REVIEW

**Comment by simonsmith** [comment]
Will give this a merge in a bit and get a new release out

**Comment by giuseppeg** [comment]
I haven't got the chance to read the airbnb conf, but yeah feel free to merge it.

maybe I would add a space between function and ( in anonymous functions

**Comment by simonsmith** [comment]
Ha, I took them out!

Think we should continue that pattern? Not one I've seen before.

**Comment by giuseppeg** [comment]
My personal preference is

```javascript
function () {}
function foo() {}
```

Not a big deal though

**Comment by simonsmith** [comment]
Ah interesting. I'm sure ESLint will be able to support that

**Comment by simonsmith** [comment]
Seems [this rule](http://eslint.org/docs/rules/no-spaced-func) is either on or off, so I'll leave it as default for now.

**Pull request merged**
