### PR TITLE
Upgrade stylelint

### LINKED ISSUE #22: Can't figure out how to activate source-map option.
I tried to generate a .map file
https://github.com/postcss/postcss/blob/master/docs/source-maps.md

package.json:
```
...
  "scripts": {
    "watch": "suitcss --watch --verbose --config config/suitcss.js source/assets/styles/main.css source/build/main.css"
  }
```

suitcss.js:
```
'use strict';

module.exports = {
  map: {
    inline: false
  }
};
```

Cant figure out where I am wrong. Any idea?

### PR DESCRIPTION
**Pull request by simonsmith**
Main change here was just to move the test expectations into the promise callback so that they aren't run too early.

Fixes #22

@giuseppeg

### CODE REVIEW

**Comment by giuseppeg** [comment]
@simonsmith cool!
Should we remove those `.catch(done)`? Imho it would be better if tests fail when the Promise is rejected.

I think that `should throw an error if stylelint fails` can be refactored too:
`suitcss(...).should.be.rejected`
or
`suitcss(...).should.be.rejectedWith(Error?, 'postcss-reporter: warnings or errors were found')`

**Comment by simonsmith** [comment]
Good idea with improving the stylelint test. I've added `chai-as-promised` for those. With regard to `.catch(done)` - they are needed to send the error back to Mocha otherwise if it rejects then the test just times out with:

> Error: timeout of 3000ms exceeded. Ensure the done() callback is being called in this test.

Couldn't see a way to use `chai-as-promised` with these tests as it's not really checking the promise fulfils, more that the stubs get called after.

**Comment by giuseppeg** [comment]
<blockquote>they are needed to send the error back to Mocha otherwise if it rejects then the test just times out with</blockquote>

When rejected is not the expected result I always let them timeout (or catch and throw). The test has to fail if something went wrong.

**Comment by simonsmith** [comment]
Currently it does fail if something goes wrong. It sends the error to `done`

**Comment by giuseppeg** [comment]
ah ok cool, I didn't know that it passes the `Error` to `done`

**Comment by giuseppeg** [comment]
@simonsmith do we need to update the docs or can I close #21 ?

**Comment by simonsmith** [comment]
Yeah its a handy shortcut that done takes an error. 

I think we can close it! I'll try out master on a component or two later and then we can release a new version. Yay. 

I also left an issue on gulp-suitcss about moving that to this org so we can maintain it. Might be useful.

**Pull request merged**
